version = 0.1

[default.deploy.parameters]
stack_name = "alexa-gemini"
resolve_s3 = true
s3_prefix = "alexa-gemini"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Runtime=\"nodejs20.x\" Architecture=\"arm64\" Handler=\"index.handler\""
image_repositories = []
